language: python
python:
  - "2.7"
install:
 -  pip install coveralls
 -  pip install nose
 -  pip install -r requirements.txt
script:
  - nosetests --with-coverage Tests
after_success:
  - coveralls
